### ISSUE TITLE
How do i Heapify?

### ISSUE THREAD

**Issue by J-Nokwal** [ElanDeyan/min_max_heap_dart#1]
I want to change the heap element to something like this how do i Heapify it  
```
var heap = MinMaxHeap(
          input: List.generate(
            10,
            (index) => StatusModel(
              status: "Done",
            localId: index,
            ),
          ),
          criteria: (element) => element.priority,
        );
        heap.printTree();
        for (var i in heap.iterable) {
          if (i.priority == 4) {
            i.priority = -i.priority;
          }
        }
        heap.printTree();
```

**Comment by ElanDeyan** [comment]
You want to change element priority?

Apologies for the delay to answer

**Comment by ElanDeyan** [comment]
The `iterable` getter doesn't make access to the element. This only return a lazy Iterable of the items present in the heap.

I'll release a big update soon. So, if you want to change element's priority and make the heapify, you can, temporarily, rebuild the heap from the Iterable.

You can, for example, use this Iterable returned, map or foreach him to change element's priority, and build a new heap from there.

**Comment by ElanDeyan** [comment]
Hello @J-Nokwal !
The new update 2.0.3 is here!
Try the new `updateWhere` method to solve your problem!

**Comment by ElanDeyan** [comment]
Alright, the new 2.1.0 version brings a change.
updateWhere now is replaceWhere. And a "new" updateWhere method is here.

To solve your problem, the updateWhere will be the right choose.

```dart
final heap = MinMaxHeap.fromIterable(
      iterable: <Task>[
        Task('Drink water', priority: 5),
        Task('Read', priority: 4),
        Task('Morning walk', priority: 3),
        Task("Review github's issues.", priority: 5),
      ],
      criteria: (element) => element.priority,
    );
    
    heap.updateWhere(
      (element) => element.priority == 3 || element.priority == 5,
      updater: (element) {
        if (element.priority == 3) {
          element.priority = 10;
          element.name = 'Changed!';
        }
        if (element.priority == 5) {
          element.priority = -1;
          element.name = 'Another change!';
        }
      },
    );
```
